# Generated by Django 4.2.1 on 2023-07-15 18:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=30)),
                ('work_zone', models.BooleanField(default=False)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('number_of_bedrooms', models.IntegerField(default=1)),
                ('space_for_people', models.IntegerField(default=1)),
                ('number_of_stars', models.PositiveBigIntegerField(default=0)),
                ('images', models.ImageField(upload_to='')),
                ('ocupation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField(default=datetime.date.today)),
                ('departure', models.DateField(default=datetime.date.today)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='accommodations',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
