# Generated by Django 4.2.1 on 2023-07-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accommodation_reservation_delete_accommodations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='images',
            field=models.ImageField(upload_to='accommodation_images/'),
        ),
    ]
