# Generated by Django 4.2.1 on 2023-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_califications_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='accommodation_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
