# Generated by Django 4.2.1 on 2023-07-12 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField(default=datetime.date.today)),
                ('departure', models.DateField(default=datetime.date.today)),
                ('ocupation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='accommodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=30)),
                ('work_zone', models.BooleanField(default=False)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('number_of_bedrooms', models.IntegerField(default=1)),
                ('space_for_people', models.IntegerField(default=1)),
                ('number_of_stars', models.PositiveBigIntegerField(default=0)),
                ('images', models.ImageField(upload_to='')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
        ),
    ]
