# Generated by Django 4.2.1 on 2023-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_accommodation_user_alter_accommodation_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='number_of_califications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='number_of_stars',
            field=models.FloatField(default=0.0),
        ),
    ]
