# Generated by Django 4.2.1 on 2023-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_califications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='califications',
            name='review',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
