# Generated by Django 4.2.1 on 2023-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_califications_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='calification',
            field=models.FloatField(default=0.0),
        ),
    ]
