# Generated by Django 4.2.1 on 2023-07-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_accommodation_calification'),
    ]

    operations = [
        migrations.AddField(
            model_name='califications',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.reservation'),
        ),
    ]
